logging:
  level:
    com.iotchallenge.sensordata.config: debug
    org.apache.kafka: warn

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      properties:
        spring.json.trusted.packages: "com.iotchallenge.sensordata.services"
      group-id: sensor-data-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

influx:
  url: http://influxdb:8086/
  username: admin
  password: admin1234
  bucket: "bucket"
  org: "org"
  token: "token"

management:
  influx:
    metrics:
      export:
        db: db0
        bucket: "bucket"
        org: "org"
        user-name: "${influx.username}"
        password: "${influx.password}"
        uri: "${influx.url}"
        token: "${influx.token}"
