spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: admin
    jpa:
        hibernate:
            show-sql: 'true'
            ddl-auto: update
